/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.AdminRole;
import Business.Role.CustomerRole;
import Business.Role.DeliverManRole;
import Business.Role.Role;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JSplitPane;

/**
 *
 * @author prathameshnemade
 */
public class AccountUpdateJPanel extends javax.swing.JPanel {

    UserAccount selectedAccount;
    int selectedIndex;
    EcoSystem system;
    UserAccount account;
    JSplitPane jSplitPane;

    /**
     * Creates new form AccountUpdateJPanel
     */
    public AccountUpdateJPanel(EcoSystem system, UserAccount account, JSplitPane jSplitPane) {
        initComponents();
        jSplitPane1.setDividerLocation((int) (0.3 * (new Dimension(Toolkit.getDefaultToolkit().getScreenSize()).width - 300)));
        this.system = system;
        this.account = account;
        this.jSplitPane = jSplitPane;
        _getDetails();
    }

    public void _getDetails() {
        DefaultListModel model = new DefaultListModel();
        ArrayList<UserAccount> accountList = this.system.getUserAccountDirectory().getUserAccountList();
        accountList.forEach(user -> {
            model.addElement(user.getUsername() + " - " + user.getRole().toString());
        });
        if (model.isEmpty()) {
            uploadedJList.setModel(model);
            JOptionPane.showMessageDialog(this, "No Profiles Created Yet!!", "View Profiles Details", ERROR_MESSAGE);
            return;
        }
        uploadedJList.setModel(model);
        uploadedJList.setSelectedIndex(0);
        openSelectedProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        updateJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        CustomerJRadioButton = new javax.swing.JRadioButton();
        confirmJPasswordField = new javax.swing.JPasswordField();
        emailIDJField = new javax.swing.JTextField();
        RestaurantManagerJRadioButton = new javax.swing.JRadioButton();
        AdminJRadioButton = new javax.swing.JRadioButton();
        JPasswordField = new javax.swing.JPasswordField();
        DeliveryManJRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uploadedJList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Profiles");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        updateJButton.setBackground(new java.awt.Color(200, 203, 178));
        updateJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        updateJButton.setForeground(new java.awt.Color(67, 100, 100));
        updateJButton.setText("UPADATE");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setBackground(new java.awt.Color(67, 100, 100));
        deleteJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        deleteJButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteJButton.setText("DELETE CAR");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        CustomerJRadioButton.setText("Customer");
        CustomerJRadioButton.setEnabled(false);
        CustomerJRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CustomerJRadioButtonFocusGained(evt);
            }
        });
        CustomerJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerJRadioButtonActionPerformed(evt);
            }
        });

        confirmJPasswordField.setBackground(new java.awt.Color(238, 238, 238));
        confirmJPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        emailIDJField.setBackground(new java.awt.Color(238, 238, 238));
        emailIDJField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailIDJField.setText("Enter email id");
        emailIDJField.setToolTipText("Click to enter your Email ID.");
        emailIDJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        emailIDJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailIDJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailIDJFieldFocusLost(evt);
            }
        });
        emailIDJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIDJFieldActionPerformed(evt);
            }
        });

        RestaurantManagerJRadioButton.setText("Restaurant Manager");
        RestaurantManagerJRadioButton.setEnabled(false);
        RestaurantManagerJRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RestaurantManagerJRadioButtonFocusGained(evt);
            }
        });
        RestaurantManagerJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurantManagerJRadioButtonActionPerformed(evt);
            }
        });

        AdminJRadioButton.setText("Admin");
        AdminJRadioButton.setEnabled(false);
        AdminJRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdminJRadioButtonFocusGained(evt);
            }
        });
        AdminJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminJRadioButtonActionPerformed(evt);
            }
        });

        JPasswordField.setBackground(new java.awt.Color(238, 238, 238));
        JPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DeliveryManJRadioButton.setText("Delivery Man");
        DeliveryManJRadioButton.setEnabled(false);
        DeliveryManJRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DeliveryManJRadioButtonFocusGained(evt);
            }
        });
        DeliveryManJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryManJRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(confirmJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIDJField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantManagerJRadioButton)
                    .addComponent(AdminJRadioButton)
                    .addComponent(JPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryManJRadioButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updateJButton)
                        .addGap(29, 29, 29)
                        .addComponent(deleteJButton))
                    .addComponent(CustomerJRadioButton))
                .addGap(252, 252, 252))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emailIDJField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(AdminJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RestaurantManagerJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeliveryManJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustomerJRadioButton)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        uploadedJList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uploadedJListFocusGained(evt);
            }
        });
        uploadedJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadedJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(uploadedJList);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Profile Details:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSplitPane1)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jSplitPane1)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openSelectedProfile() {
        selectedIndex = uploadedJList.getSelectedIndex();
        ArrayList<UserAccount> accountList = this.system.getUserAccountDirectory().getUserAccountList();
        if (selectedIndex != -1) {
            selectedAccount = accountList.get(selectedIndex);
            System.out.println("selectedAccount" + selectedAccount.getUsername());
            this.emailIDJField.setText(selectedAccount.getUsername());
            if (null == selectedAccount.getRole().toString()) {
//                JOptionPane.showMessageDialog(this, "No Profiles Created Yet!!", "View Profiles Details", ERROR_MESSAGE);
            } else {
                switch (selectedAccount.getRole().toString()) {
                    case "Business.Role.SystemAdminRole":
                        this.AdminJRadioButton.setSelected(true);
                        this.RestaurantManagerJRadioButton.setSelected(false);
                        this.DeliveryManJRadioButton.setSelected(false);
                        this.CustomerJRadioButton.setSelected(false);
                        break;
                    case "Business.Role.AdminRole":
                        this.RestaurantManagerJRadioButton.setSelected(true);
                        this.AdminJRadioButton.setSelected(false);
                        this.CustomerJRadioButton.setSelected(false);
                        this.DeliveryManJRadioButton.setSelected(false);
                        break;
                    case "Business.Role.DeliverManROle":
                        this.DeliveryManJRadioButton.setSelected(true);
                        this.AdminJRadioButton.setSelected(false);
                        this.CustomerJRadioButton.setSelected(false);
                        this.RestaurantManagerJRadioButton.setSelected(false);
                        break;
                    default:
                        this.CustomerJRadioButton.setSelected(true);
                        this.AdminJRadioButton.setSelected(false);
                        this.RestaurantManagerJRadioButton.setSelected(false);
                        this.DeliveryManJRadioButton.setSelected(false);
                        break;
                }
            }
        }
    }
    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        selectedIndex = uploadedJList.getSelectedIndex();
        if (selectedIndex != -1) {
            if (emailIDJField != null && JPasswordField.getPassword() != null) {
                String password = new String(JPasswordField.getPassword());
                String confirmPassword = new String(confirmJPasswordField.getPassword());
                if (password.equals(confirmPassword)) {
                    if (this.system.getUserAccountDirectory().checkIfUsernameIsUnique(this.emailIDJField.getText())) {
                        Role role;
                        Employee employee = new Employee();
                        employee.setName(this.emailIDJField.getText());
                        if (AdminJRadioButton.isSelected()) {
                            role = new SystemAdminRole();
                        } else if (RestaurantManagerJRadioButton.isSelected()) {
                            role = new AdminRole();
                        } else if (DeliveryManJRadioButton.isSelected()) {
                            role = new DeliverManRole();
                        } else {
                            role = new CustomerRole();
                        }
                        this.selectedAccount.setPassword(password);
                        this.selectedAccount.setUsername(this.emailIDJField.getText());
                        JOptionPane.showMessageDialog(this, "User updated successfully!!", "Register", INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this, "EmailId already used!!", "Register", ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password and Confirm Password should match!", "Register", ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username or Password requried.", "Register", ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        selectedIndex = uploadedJList.getSelectedIndex();
        if (selectedIndex != -1) {
            this.system.getUserAccountDirectory().getUserAccountList().remove(this.selectedIndex);
            uploadedJList.setSelectedIndex(0);
            openSelectedProfile();
        }
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void uploadedJListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uploadedJListFocusGained
        openSelectedProfile();
    }//GEN-LAST:event_uploadedJListFocusGained

    private void uploadedJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadedJListMouseClicked
        openSelectedProfile();
    }//GEN-LAST:event_uploadedJListMouseClicked

    private void CustomerJRadioButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CustomerJRadioButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerJRadioButtonFocusGained

    private void CustomerJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerJRadioButtonActionPerformed
        this.AdminJRadioButton.setSelected(false);
        this.DeliveryManJRadioButton.setSelected(false);
        this.RestaurantManagerJRadioButton.setSelected(false);
    }//GEN-LAST:event_CustomerJRadioButtonActionPerformed

    private void emailIDJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDJFieldFocusGained
        if (emailIDJField.getText().equals("Enter email id")) {
            emailIDJField.setText("");
        }
    }//GEN-LAST:event_emailIDJFieldFocusGained

    private void emailIDJFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDJFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDJFieldFocusLost

    private void emailIDJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIDJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDJFieldActionPerformed

    private void RestaurantManagerJRadioButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RestaurantManagerJRadioButtonFocusGained
        AdminJRadioButton.setSelected(false);
    }//GEN-LAST:event_RestaurantManagerJRadioButtonFocusGained

    private void RestaurantManagerJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurantManagerJRadioButtonActionPerformed
        this.AdminJRadioButton.setSelected(false);
        this.CustomerJRadioButton.setSelected(false);
        this.DeliveryManJRadioButton.setSelected(false);
    }//GEN-LAST:event_RestaurantManagerJRadioButtonActionPerformed

    private void AdminJRadioButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminJRadioButtonFocusGained
        RestaurantManagerJRadioButton.setSelected(false);
    }//GEN-LAST:event_AdminJRadioButtonFocusGained

    private void AdminJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminJRadioButtonActionPerformed
        this.RestaurantManagerJRadioButton.setSelected(false);
        this.CustomerJRadioButton.setSelected(false);
        this.DeliveryManJRadioButton.setSelected(false);
    }//GEN-LAST:event_AdminJRadioButtonActionPerformed

    private void DeliveryManJRadioButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DeliveryManJRadioButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryManJRadioButtonFocusGained

    private void DeliveryManJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryManJRadioButtonActionPerformed
        this.AdminJRadioButton.setSelected(false);
        this.CustomerJRadioButton.setSelected(false);
        this.RestaurantManagerJRadioButton.setSelected(false);
    }//GEN-LAST:event_DeliveryManJRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminJRadioButton;
    private javax.swing.JRadioButton CustomerJRadioButton;
    private javax.swing.JRadioButton DeliveryManJRadioButton;
    private javax.swing.JPasswordField JPasswordField;
    private javax.swing.JRadioButton RestaurantManagerJRadioButton;
    private javax.swing.JPasswordField confirmJPasswordField;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JTextField emailIDJField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton updateJButton;
    private javax.swing.JList<String> uploadedJList;
    // End of variables declaration//GEN-END:variables
}
