/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderAssignmentRequest;
import Business.WorkQueue.OrderDelieveryRequest;
import Business.WorkQueue.OrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JSplitPane;

/**
 *
 * @author prathameshnemade
 */
public class OrderDeliveryStatusJPanel extends javax.swing.JPanel {

    EcoSystem ecosystem;
    UserAccount account;
    JSplitPane jSplitPane;
    UserAccount selectedDeliveryMen;
    ArrayList<UserAccount> onlyDeliveryMens = new ArrayList<UserAccount>();
    ArrayList<OrderAssignmentRequest> allReadyToPickUpOrders = new ArrayList<OrderAssignmentRequest>();
    OrderAssignmentRequest selectedOrder;

    OrderDeliveryStatusJPanel(EcoSystem ecosystem, UserAccount account, JSplitPane jSplitPane) {
        this.ecosystem = ecosystem;
        this.account = account;
        this.jSplitPane = jSplitPane;
        initComponents();
        this.ordersJList.setVisible(false);
        this.jLabel5.setVisible(false);
        this.statusJComboBox.setVisible(false);
        this.addJButton1.setVisible(false);
        _getDeliveryMenList();
        setDeliveryMen();
    }

    public void _getDeliveryMenList() {
        ArrayList<String> menuNameDropdown = new ArrayList<>();

        for (int i = 0; i < this.ecosystem.getUserAccountDirectory().getUserAccountList().size(); i++) {
            UserAccount ongoing = this.ecosystem.getUserAccountDirectory().getUserAccountList().get(i);
            if ("Business.Role.DeliverManRole".equals(ongoing.getRole().toString())) {
                this.onlyDeliveryMens.add(ongoing);
                menuNameDropdown.add(ongoing.getUsername());
            }
        }

        String[] menuSDropdown = menuNameDropdown.toArray(new String[menuNameDropdown.size()]);
        DefaultComboBoxModel<String> brandSDropdownModel = new DefaultComboBoxModel<>(menuSDropdown);
        this.deliveryMenJComboBox.setModel(brandSDropdownModel);
    }

    public void _getUnAssignedOrders() {
        DefaultListModel model = new DefaultListModel();
        this.ordersJList.setModel(model);
        allReadyToPickUpOrders = new ArrayList<OrderAssignmentRequest>();

        for (int i = 0; i < this.ecosystem.getWorkQueue().getWorkRequestList().size(); i++) {
            WorkRequest ongoing = this.ecosystem.getWorkQueue().getWorkRequestList().get(i);
            if (ongoing instanceof OrderAssignmentRequest) {
                OrderAssignmentRequest onGo = (OrderAssignmentRequest) ongoing;
                System.out.println(onGo.getAssignmentStatus());
                System.out.println(onGo.getAssignmentTo());
                System.out.println(this.selectedDeliveryMen.getUsername());

                if ((onGo.getAssignmentStatus().toString().equals("READYFORPICKUP") || onGo.getAssignmentStatus().toString().equals("PICKED")) && onGo.getAssignmentTo().getUsername() == this.selectedDeliveryMen.getUsername()) {
                    String address = ongoing.getAddress().toString();
                    Long resWorkId = ((OrderAssignmentRequest) ongoing).getAssignmentId();
                    model.addElement(String.valueOf(resWorkId) + " - " + address);
                    allReadyToPickUpOrders.add((OrderAssignmentRequest) ongoing);
                }
            }
        }
        this.ordersJList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        deliveryMenJComboBox = new javax.swing.JComboBox<>();
        addJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersJList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        statusJComboBox = new javax.swing.JComboBox<>();
        addJButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        createdAtJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        commentsJLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        customerJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select a deliverymen:");

        deliveryMenJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deliveryMenJComboBoxItemStateChanged(evt);
            }
        });

        addJButton.setBackground(new java.awt.Color(200, 203, 178));
        addJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addJButton.setForeground(new java.awt.Color(67, 100, 100));
        addJButton.setText("SEARCH");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        ordersJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ordersJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ordersJList);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Set Status:");

        statusJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PICKED", "DELIVERED" }));
        statusJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statusJComboBoxItemStateChanged(evt);
            }
        });

        addJButton1.setBackground(new java.awt.Color(200, 203, 178));
        addJButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addJButton1.setForeground(new java.awt.Color(67, 100, 100));
        addJButton1.setText("DONE");
        addJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Noto Sans Oriya", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 100, 100));
        jLabel6.setText("Order Created At:");

        createdAtJLabel.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        createdAtJLabel.setForeground(new java.awt.Color(67, 100, 100));
        createdAtJLabel.setText("Select a order!");

        jLabel7.setFont(new java.awt.Font("Noto Sans Oriya", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(67, 100, 100));
        jLabel7.setText("Comments");

        commentsJLabel.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        commentsJLabel.setForeground(new java.awt.Color(67, 100, 100));
        commentsJLabel.setText("Select a order!");

        jLabel8.setFont(new java.awt.Font("Noto Sans Oriya", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(67, 100, 100));
        jLabel8.setText("Address");

        addressJLabel.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        addressJLabel.setForeground(new java.awt.Color(67, 100, 100));
        addressJLabel.setText("Select a order!");

        jLabel9.setFont(new java.awt.Font("Noto Sans Oriya", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(67, 100, 100));
        jLabel9.setText("Customer");

        customerJLabel.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        customerJLabel.setForeground(new java.awt.Color(67, 100, 100));
        customerJLabel.setText("Select a order!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deliveryMenJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createdAtJLabel)
                            .addComponent(addressJLabel)
                            .addComponent(commentsJLabel)
                            .addComponent(customerJLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(addJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(createdAtJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryMenJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(commentsJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(addressJLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(customerJLabel)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(addJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(196, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryMenJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deliveryMenJComboBoxItemStateChanged
        setDeliveryMen();
    }//GEN-LAST:event_deliveryMenJComboBoxItemStateChanged

    public void setDeliveryMen() {
        Integer selectedIndex = this.deliveryMenJComboBox.getSelectedIndex();
        if (selectedIndex != -1) {
            this.selectedDeliveryMen = this.onlyDeliveryMens.get(selectedIndex);
        }
    }

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        _getUnAssignedOrders();
        this.ordersJList.setVisible(true);
    }//GEN-LAST:event_addJButtonActionPerformed

    private void ordersJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ordersJListValueChanged
        openSelectedOrder();
        this.jLabel5.setVisible(true);
        this.statusJComboBox.setVisible(true);
        this.addJButton1.setVisible(true);
    }//GEN-LAST:event_ordersJListValueChanged

    private void statusJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statusJComboBoxItemStateChanged
        //todo
    }//GEN-LAST:event_statusJComboBoxItemStateChanged

    public void openSelectedOrder() {
        Integer selectedOrderIndex = this.ordersJList.getSelectedIndex();
        if (selectedOrderIndex != -1) {
            selectedOrder = this.allReadyToPickUpOrders.get(selectedOrderIndex);
            this.createdAtJLabel.setText(this.selectedOrder.getOrderAssignmentAt().toString());
            this.commentsJLabel.setText(this.selectedOrder.getAssignmentComments());
            this.addressJLabel.setText(this.selectedOrder.getAddress());
            this.customerJLabel.setText(this.selectedOrder.getReceiver().getUsername());
        }
    }

    private void addJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButton1ActionPerformed
        for (int i = 0; i < this.ecosystem.getWorkQueue().getWorkRequestList().size(); i++) {
            WorkRequest ongoing = this.ecosystem.getWorkQueue().getWorkRequestList().get(i);
            if (ongoing instanceof OrderAssignmentRequest) {
                OrderAssignmentRequest onGo = (OrderAssignmentRequest) ongoing;
                if (onGo.getAssignmentId() == this.selectedOrder.getAssignmentId()) {
                    onGo.setAssignmentStatus(this.statusJComboBox.getSelectedItem().toString());

                    if (this.statusJComboBox.getSelectedItem().toString() == "DELIVERED") {
                        onGo.setResolveDate(new Date());
                    }
//                    if (this.statusJComboBox.getSelectedItem().toString() == "DELIVERED") {
                    onGo.setStatus(this.statusJComboBox.getSelectedItem().toString());
                    for (int j = 0; j < this.ecosystem.getWorkQueue().getWorkRequestList().size(); j++) {
                        WorkRequest ongoing1 = this.ecosystem.getWorkQueue().getWorkRequestList().get(j);
                        if (ongoing1 instanceof OrderDelieveryRequest) {
                            OrderDelieveryRequest toChnage = (OrderDelieveryRequest) ongoing1;
                            if (toChnage.getDeliveryRequestId() == onGo.getAssignmentId()) {
                                toChnage.setDeliveryStatus(this.statusJComboBox.getSelectedItem().toString());
                                toChnage.setStatus(this.statusJComboBox.getSelectedItem().toString());

                                if (this.statusJComboBox.getSelectedItem().toString() == "DELIVERED") {
                                    toChnage.setResolveDate(new Date());
                                }
                            }
                        } else if (ongoing1 instanceof OrderWorkRequest) {
                            OrderWorkRequest toChnage = (OrderWorkRequest) ongoing1;
                            if ((toChnage.getOrderWorkRequestId()) == onGo.getAssignmentId()) {
                                toChnage.setOrderRequestStatus(this.statusJComboBox.getSelectedItem().toString());
                                toChnage.setStatus(this.statusJComboBox.getSelectedItem().toString());

                                if (this.statusJComboBox.getSelectedItem().toString() == "DELIVERED") {
                                    toChnage.setResolveDate(new Date());
                                }
                            }
                        }
//                        }
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Status changed Successfully!", "Delivery Status Details", INFORMATION_MESSAGE);

        this.ordersJList.setVisible(false);
        this.jLabel5.setVisible(false);
        this.statusJComboBox.setVisible(false);
        this.addJButton1.setVisible(false);
        this.createdAtJLabel.setText("Select a order!");
        this.commentsJLabel.setText("Select a order!");
        this.addressJLabel.setText("Select a order!");
        this.customerJLabel.setText("Select a order!");
        _getDeliveryMenList();
        setDeliveryMen();
    }//GEN-LAST:event_addJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton addJButton1;
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JLabel commentsJLabel;
    private javax.swing.JLabel createdAtJLabel;
    private javax.swing.JLabel customerJLabel;
    private javax.swing.JComboBox<String> deliveryMenJComboBox;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> ordersJList;
    private javax.swing.JComboBox<String> statusJComboBox;
    // End of variables declaration//GEN-END:variables
}
