/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JSplitPane;

/**
 *
 * @author prathameshnemade
 */
public class RestaurantModifyMenuJPanel extends javax.swing.JPanel {

    EcoSystem system;
    UserAccount account;
    JSplitPane jSplitPane;
    HashMap<String, Double> resMenu = new HashMap<String, Double>();
    Integer selectedIndex = -1;
    Restaurant selectedRes;

    RestaurantModifyMenuJPanel(EcoSystem system, UserAccount account, JSplitPane jSplitPane) {
        this.system = system;
        this.account = account;
        this.jSplitPane = jSplitPane;
        initComponents();
        _getMenu();
        _setMenuList();
        if (this.selectedRes == null) {
            JOptionPane.showMessageDialog(this, "No hotels under you yet!", "Modify Menu", ERROR_MESSAGE);
        }
        if (resMenu.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No menu created yet under the hotel allocated to you!", "Modify Menu", ERROR_MESSAGE);
        }
    }

    public void _getMenu() {
        for (int i = 0; i < this.system.getRestaurantDirectory().getRestaurantList().size(); i++) {
            Restaurant ongoing = this.system.getRestaurantDirectory().getRestaurantList().get(i);
            System.out.println("ongoing.getManagerUserName()" + ongoing.getManagerUserName() + "|" + this.account.getUsername());
            if (ongoing.getManagerUserName().toString().equals(this.account.getUsername().toString())) {
                resMenu = ongoing.getMenu();
                selectedRes = ongoing;
            }
        }
    }

    public void _setMenuList() {
        DefaultListModel model = new DefaultListModel();
        jList1.setModel(model);
        for (Iterator<Map.Entry<String, Double>> it = this.resMenu.entrySet().iterator(); it.hasNext();) {
            HashMap.Entry<String, Double> set = it.next();
            model.addElement(set.getKey() + " - " + set.getValue());
        }
        jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialNoJLabel1 = new javax.swing.JLabel();
        menuNameJField = new javax.swing.JTextField();
        menuPriceJField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        serialNoJLabel1.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        serialNoJLabel1.setForeground(new java.awt.Color(67, 100, 100));
        serialNoJLabel1.setText("Modify Menu(*):");

        menuNameJField.setBackground(new java.awt.Color(238, 238, 238));
        menuNameJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        menuNameJField.setText("Enter here");
        menuNameJField.setToolTipText("Click to enter your name.");
        menuNameJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        menuNameJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuNameJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                menuNameJFieldnameChangeHandler(evt);
            }
        });
        menuNameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNameJFieldActionPerformed(evt);
            }
        });

        menuPriceJField.setBackground(new java.awt.Color(238, 238, 238));
        menuPriceJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        menuPriceJField.setText("Enter here");
        menuPriceJField.setToolTipText("Click to enter your name.");
        menuPriceJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        menuPriceJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuPriceJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                menuPriceJFieldnameChangeHandler(evt);
            }
        });
        menuPriceJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPriceJFieldActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(200, 203, 178));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(67, 100, 100));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setBackground(new java.awt.Color(200, 203, 178));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(67, 100, 100));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(200, 203, 178));
        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(200, 203, 178));
        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(67, 100, 100));
        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(serialNoJLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuNameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuPriceJField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuNameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNoJLabel1)
                    .addComponent(menuPriceJField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuNameJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuNameJFieldFocusGained
        if (menuNameJField.getText().equals("Enter here")) {
            menuNameJField.setText("");
        }
    }//GEN-LAST:event_menuNameJFieldFocusGained

    private void menuNameJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuNameJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNameJFieldnameChangeHandler

    private void menuNameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNameJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNameJFieldActionPerformed

    private void menuPriceJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuPriceJFieldFocusGained
        if (menuPriceJField.getText().equals("Enter here")) {
            menuPriceJField.setText("");
        }
    }//GEN-LAST:event_menuPriceJFieldFocusGained

    private void menuPriceJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuPriceJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPriceJFieldnameChangeHandler

    private void menuPriceJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPriceJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPriceJFieldActionPerformed

    public boolean validateMenuEntry() {
        RestaurantDirectory dummy = this.system.getRestaurantDirectory();
        String errorMessage = "";
        String errorName = dummy.validateName(this.menuNameJField.getText());
        String errorPrice = dummy.validatePrice(this.menuPriceJField.getText());
        errorMessage += errorName;
        errorMessage += errorPrice;

        if (errorMessage.equals("")) {
            return true;
        }
        JOptionPane.showMessageDialog(this, errorMessage, "Create Restaurant", ERROR_MESSAGE);
        return false;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.selectedIndex != -1) {
            Integer count = 0;
            for (HashMap.Entry<String, Double> entry : this.resMenu.entrySet()) {
                String key = entry.getKey();
                Double value = entry.getValue();
                if (count == this.selectedIndex) {
                    this.menuNameJField.setText(key);
                    this.menuPriceJField.setText(String.valueOf(value));
                }
                count += 1;
            }
            _getMenu();
            _setMenuList();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a menu to Update!", "Update Menu", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        this.selectedIndex = this.jList1.getSelectedIndex();
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Boolean valid = validateMenuEntry();
        if (valid) {
            this.resMenu.put(this.menuNameJField.getText(), Double.parseDouble(this.menuPriceJField.getText()));
            _getMenu();
            _setMenuList();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (this.selectedIndex != -1) {
            String key = null;
            Integer count = 0;
            for (HashMap.Entry<String, Double> entry : this.resMenu.entrySet()) {
                if (count == this.selectedIndex) {
                    key = entry.getKey();
                }
                count += 1;
            }
            this.resMenu.remove(key);
            _getMenu();
            _setMenuList();

        } else {
            JOptionPane.showMessageDialog(this, "Please select a menu to Delete!", "Delete Menu", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for (int i = 0; i < this.system.getRestaurantDirectory().getRestaurantList().size(); i++) {
            Restaurant ongoing = this.system.getRestaurantDirectory().getRestaurantList().get(i);
            if (ongoing == this.selectedRes) {
                ongoing.setMenu(resMenu);
            }
        }
        _getMenu();
        _setMenuList();
        JOptionPane.showMessageDialog(this, "Menu modififed successfully!!", "Modidy Menu", INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField menuNameJField;
    private javax.swing.JTextField menuPriceJField;
    private javax.swing.JLabel serialNoJLabel1;
    // End of variables declaration//GEN-END:variables
}
