/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.Customer;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.AdminRole;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author prathameshnemade
 */
public class RegisterPage extends javax.swing.JPanel {

    private JFrame rootFrame;
    private JPanel rootJPanel;
    private JButton logoutJButton;
    private EcoSystem system;

    /**
     * Creates new form LoginPage
     *
     * @param jSplitPane
     * @param leftJPanel
     * @param rightJPanel
     * @param logoutJButton
     * @param system
     */
    public RegisterPage(JFrame rootFrame, JPanel rootJPanel, JButton logoutJButton, EcoSystem system) {
        initComponents();
        this.rootFrame = rootFrame;
        this.rootJPanel = rootJPanel;
        this.logoutJButton = logoutJButton;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerJButton = new javax.swing.JButton();
        passwordJField = new javax.swing.JTextField();
        emailIDJField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        confirmPasswordJField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        registerJButton.setBackground(new java.awt.Color(200, 203, 178));
        registerJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        registerJButton.setForeground(new java.awt.Color(67, 100, 100));
        registerJButton.setText("Register");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        passwordJField.setBackground(new java.awt.Color(238, 238, 238));
        passwordJField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordJField.setText("Enter password");
        passwordJField.setToolTipText("Click to enter your Password.");
        passwordJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        passwordJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordJFieldFocusLost(evt);
            }
        });
        passwordJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJFieldActionPerformed(evt);
            }
        });

        emailIDJField.setBackground(new java.awt.Color(238, 238, 238));
        emailIDJField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailIDJField.setText("Enter email id");
        emailIDJField.setToolTipText("Click to enter your Email ID.");
        emailIDJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        emailIDJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailIDJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailIDJFieldFocusLost(evt);
            }
        });
        emailIDJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIDJFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Already have an account? Click to Login");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        confirmPasswordJField.setBackground(new java.awt.Color(238, 238, 238));
        confirmPasswordJField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPasswordJField.setText("Enter password");
        confirmPasswordJField.setToolTipText("Click to enter your Password.");
        confirmPasswordJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        confirmPasswordJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordJFieldFocusLost(evt);
            }
        });
        confirmPasswordJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordJFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(registerJButton)
                    .addComponent(jButton1)
                    .addComponent(passwordJField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIDJField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmPasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(174, 174, 174)
                .addComponent(emailIDJField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordJField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmPasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String validateregister() {
        String isValid = "";

        if (this.emailIDJField == null) {
            isValid += "Email Id required! \n";
        }
        if (this.passwordJField == null) {
            isValid += "Password is required! \n";
        }
        if (!this.confirmPasswordJField.getText().equals(this.passwordJField.getText())) {
            isValid += "Confirm Password should be same as Password! \n";
        }
        if (this.system.checkIfUserIsUnique(this.emailIDJField.getText())) {
            isValid += "Username already used! \n";
        }
        return isValid;
    }

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        String isValid = this.validateregister();
        if (isValid.equals("")) {
            Employee employee = new Employee();
            employee.setName(this.emailIDJField.getText());
//            this.system.getUserAccountDirectory().createUserAccount("admin", "admin", employee, new CustomerRole());
//           
            UserAccount user = new UserAccount();
            user.setEmployee(employee);
            user.setPassword(this.passwordJField.getText());
            user.setUsername(this.emailIDJField.getText());
            user.setRole(new AdminRole());
            (DB4OUtil.getInstance()).storeSystem(system);

            JOptionPane.showMessageDialog(this, "Registered Successfully!", "Register", INFORMATION_MESSAGE);

            LoginPage loginPage = new LoginPage(this.rootFrame, this.rootJPanel, this.logoutJButton, system);
            this.rootJPanel.add(loginPage);
            CardLayout layout = (CardLayout) this.rootJPanel.getLayout();
            layout.next(this.rootJPanel);

        } else {
            JOptionPane.showMessageDialog(this, isValid, "Register", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerJButtonActionPerformed

    private void passwordJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJFieldFocusGained
        if (passwordJField.getText().equals("Enter password")) {
            passwordJField.setText("");
        }
    }//GEN-LAST:event_passwordJFieldFocusGained

    private void passwordJFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJFieldFocusLost

    }//GEN-LAST:event_passwordJFieldFocusLost

    private void passwordJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJFieldActionPerformed

    private void emailIDJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDJFieldFocusGained
        if (emailIDJField.getText().equals("Enter email id")) {
            emailIDJField.setText("");
        }
    }//GEN-LAST:event_emailIDJFieldFocusGained

    private void emailIDJFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDJFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDJFieldFocusLost

    private void emailIDJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIDJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDJFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginPage loginPage = new LoginPage(this.rootFrame, this.rootJPanel, this.logoutJButton, system);
        this.rootJPanel.add(loginPage);
        CardLayout layout = (CardLayout) this.rootJPanel.getLayout();
        layout.next(this.rootJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmPasswordJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordJFieldFocusGained
        if (confirmPasswordJField.getText().equals("Enter password")) {
            confirmPasswordJField.setText("");
        }
    }//GEN-LAST:event_confirmPasswordJFieldFocusGained

    private void confirmPasswordJFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordJFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordJFieldFocusLost

    private void confirmPasswordJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordJFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmPasswordJField;
    private javax.swing.JTextField emailIDJField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField passwordJField;
    private javax.swing.JButton registerJButton;
    // End of variables declaration//GEN-END:variables
}
