/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import assignment01.Person;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static ui.CreateProfileJPanel.PROFILE_HEIGHT;
import static ui.CreateProfileJPanel.PROFILE_WIDTH;

/**
 *
 * @author prathameshnemade
 */
public class ViewAllProfilesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllProfilesJPanel
     *
     * @param person
     * @throws java.io.IOException set all the values to show the profile
     */
    public ViewAllProfilesJPanel(Person person) throws IOException {
        initComponents();
        newInitComponents();
        setProfilePicture(person.profilePicture);
        nameJLabel.setText(person.name);
        addressJTextArea.setText(person.address);
        dobJLabel.setText(String.valueOf(person.dateOfBirth));
        phoneJLabel.setText("+1 (" + person.telephoneAreaCode + ") " + person.telephoneNumber);
        faxJLabel.setText("+1 (" + person.faxAreaCode + ") " + person.faxNumber);
        emailJLabel.setText(person.email);
        ssnJLabel.setText(String.valueOf(person.getSsnNumber()));
        mrnJLabel.setText(String.valueOf(person.getMedicalRecordNumber()));
        healthBeneficiaryJLabel.setText(person.getHealthBeneficiaryNumber());
        bankAccountJLabel.setText(String.valueOf(person.getBankAccountNumber()));
        certificateNoJLabel.setText(String.valueOf(person.getCertificateNumber()));
        licenseNoJLabel.setText(person.getVehicleLicenseNumber());
        linkedinURLJLabel.setText(person.linkedinUrl);
        ipJLabel.setText(person.getIpAddress());
        identifierJLabel.setText(String.valueOf(person.profileId));
    }

    /**
     *
     * @param path
     * @throws IOException. path is the Absolute path of the file.
     */
    public void setProfilePicture(String path) throws IOException {
        BufferedImage img = ImageIO.read(new File(path));
        Image getImageSource = new ImageIcon(img).getImage();
        profileImageJLabel.setIcon(new ImageIcon(getImageSource.getScaledInstance(PROFILE_WIDTH, PROFILE_HEIGHT, Image.SCALE_SMOOTH)));
    }

    private void newInitComponents() {
        /**
         * Set the left section as 40% and right as 60%;
         */
        jSplitPane1.setDividerLocation((int) (0.4 * (new Dimension(Toolkit.getDefaultToolkit().getScreenSize()).width - 300)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        profileImageJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressJTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        faxJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ssnJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mrnJLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        healthBeneficiaryJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bankAccountJLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        certificateNoJLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        licenseNoJLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        linkedinURLJLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ipJLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        identifierJLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        headingJLabel.setFont(new java.awt.Font("Gujarati Sangam MN", 1, 18)); // NOI18N
        headingJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingJLabel.setText("Create a Profile");
        headingJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        profileImageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSplitPane1.setDividerSize(0);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        nameJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nameJLabel.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Address:");

        addressJTextArea.setEditable(false);
        addressJTextArea.setBackground(new java.awt.Color(238, 238, 238));
        addressJTextArea.setColumns(20);
        addressJTextArea.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addressJTextArea.setRows(5);
        jScrollPane1.setViewportView(addressJTextArea);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Date of Birth:");

        dobJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        dobJLabel.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("FAX No.:");

        phoneJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        phoneJLabel.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Phone No:");

        faxJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        faxJLabel.setText("jLabel7");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        emailJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        emailJLabel.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameJLabel)
                            .addComponent(dobJLabel)
                            .addComponent(phoneJLabel)
                            .addComponent(faxJLabel)
                            .addComponent(emailJLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameJLabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dobJLabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneJLabel)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(faxJLabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("SSN:");

        ssnJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ssnJLabel.setText("jLabel5");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("MRN:");

        mrnJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mrnJLabel.setText("jLabel5");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Health Beneficiary No.:");

        healthBeneficiaryJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        healthBeneficiaryJLabel.setText("jLabel5");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Bank Account No.:");

        bankAccountJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bankAccountJLabel.setText("jLabel5");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Certificate No.:");

        certificateNoJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        certificateNoJLabel.setText("jLabel5");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("LinkedIn URL:");

        licenseNoJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        licenseNoJLabel.setText("jLabel5");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setText("License No.:");

        linkedinURLJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        linkedinURLJLabel.setText("jLabel5");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setText("IP Address:");

        ipJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ipJLabel.setText("jLabel5");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setText("Profile Indentifier:");

        identifierJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        identifierJLabel.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licenseNoJLabel)
                    .addComponent(certificateNoJLabel)
                    .addComponent(bankAccountJLabel)
                    .addComponent(healthBeneficiaryJLabel)
                    .addComponent(mrnJLabel)
                    .addComponent(ssnJLabel)
                    .addComponent(linkedinURLJLabel)
                    .addComponent(ipJLabel)
                    .addComponent(identifierJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ssnJLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mrnJLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(healthBeneficiaryJLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bankAccountJLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(certificateNoJLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNoJLabel)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(linkedinURLJLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ipJLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(identifierJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileImageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileImageJLabel)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(headingJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingJLabel)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressJTextArea;
    private javax.swing.JLabel bankAccountJLabel;
    private javax.swing.JLabel certificateNoJLabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JLabel faxJLabel;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel healthBeneficiaryJLabel;
    private javax.swing.JLabel identifierJLabel;
    private javax.swing.JLabel ipJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel licenseNoJLabel;
    private javax.swing.JLabel linkedinURLJLabel;
    private javax.swing.JLabel mrnJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel phoneJLabel;
    private javax.swing.JLabel profileImageJLabel;
    private javax.swing.JLabel ssnJLabel;
    // End of variables declaration//GEN-END:variables
}
